### ISSUE TITLE
TypeError: run_process() got an unexpected keyword argument 'process_args'

### ISSUE THREAD

**Issue by frankcorneliusmartin** [samuelcolvin/watchgod#37]
The example in the readme indicated there is a process_args lkeyword argument, but when I try the example I get the following error:
```TypeError: run_process() got an unexpected keyword argument 'process_args'```

Did I miss anything?

**Comment by isvoboda** [comment]
It seems the signature of `run_process` differs from the one in the `README.rst`. Use the keyword `args` instead of `process_args`. The definition is [here](https://github.com/samuelcolvin/watchgod/blob/b8f9ebb17206a7210690c673173a0d863d4e0f62/watchgod/main.py#L148).

`README.rst` should be updated.

**Comment by samuelcolvin** [comment]
sorry about that, PR welcome to fix this.
