### ISSUE TITLE
Need to be able to watch multiple paths

### ISSUE THREAD

**Issue by jclosure** [samuelcolvin/watchgod#65]
There are cases where bits of an application are under multiple directories.  If watchgod's path param accepted a PATH_STRING, then it could support apps that are distributed between multiple disparate places in the file_system.  

e.g. 
```bash
$ watchgod mymodule.main "/foo/abc:/bar/cde"
```

Cases where this is relevant are:
> 1.  where PYTHON_PATH is being used for module resolution
> 2. `pip install -e .` or `python setup.py develop` are being used to work on code in multiple unrelated dirs

The implementation could just split the path on `:` and then create watchers for each.  If no seperator, exists it would behave equivalently with single path invocation.

**Comment by JosXa** [comment]
I am working on a framework and would like to build a hot module reload functionality. For this, I gathered a dependency tree of files that a given module depends on and flattened them into a single list, only to realize that watchgod does not support listening on multiple file paths in bulk :/ 
Is this possible with workarounds like `asyncio.gather(...)`, or would that result in a big performance overhead?

**Comment by akurani** [comment]
I managed to watch multiple paths with multiple async watchers and asyncio.gather (riffing off this answer from SO: <https://stackoverflow.com/a/57877288>). Here's the boilerplate version:

```python
import asyncio
from watchgod.main import awatch


async def watch_path_a():
    async for changes in awatch("path_a"):
        print(changes)


async def watch_path_b():
    async for changes in awatch("path_b"):
        print(changes)


async def main():
    await asyncio.gather(
        watch_path_a(),
        watch_path_b(),
    )

asyncio.get_event_loop().run_until_complete(main())
```

It seems to work in my limited testing. I'll update here if I encounter any issues.

**Comment by amirkdv** [comment]
I think this is a common enough use case to support [^1].

Here's a slightly more generalized version of the solution by @akurani:

```py
async def awatchn(paths, callback=print):
    async def _watch_single(path):
        async for changes in watchgod.awatch(path):
            callback(changes)

    await asyncio.gather(*[_watch_single(path) for path in paths])
```

that can be used like so:
```py
async def main():
    await awatchn(['foo.txt', 'foodir'])

if __name__ == '__main__':
    asyncio.run(main())
```

### Caveat, and a more involved solution

The above hides the async generator aspect of `watchgod` (note the callback passing), i.e. it does not allow me to do things like this:

```py
async for changes in awatchn(['foo.txt', 'foodir']):
    print(changes)
```

Here's a prototype for a proper async generator that _can_ be used like above.

```py
class awatchn:
    def __init__(self, paths, **kwargs):
        self._queue = asyncio.Queue()
        self._iterators = [self._awatch_single(path, **kwargs) for path in paths]
        self._futures = []

    def __aiter__(self):
        self._futures = [asyncio.ensure_future(it) for it in self._iterators]
        return self

    async def __anext__(self):
        if self._done():
            raise StopAsyncIteration

        return await self._queue.get()

    def _done(self):
        return all(f.done() for f in self._futures) and self._queue.empty()

    async def _awatch_single(self, path, **kwargs):
        async for changes in watchgod.awatch(path, **kwargs):
            await self._queue.put(changes)
            await asyncio.sleep(0)
```

This approach (merging multiple async generators) seems a lot easier to me than changing the implementation of `awatch` directly but then there would be an unnecessary distinction (from the user's pov) between `awatch` and `awatchn`. @samuelcolvin Do you think this is worth a PR?

----

[^1]: Here's my use case. I have a sphinx project like this

    project-root/
      conf.py   # sphinx config
      src/      # rouce rst files
      out/      # built site, output of sphinx-build
      static/   # css, js, image files

And I want to use watchgod to make a build script that watches for changes in either of `conf.py`, `src/` or `static/`. Using the parent directory doesn't work because it contains the output of build `out/`.

**Comment by samuelcolvin** [comment]
done in #98.
